# Generated by Django 4.1 on 2023-04-25 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='addloc_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locationadd', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='adminlogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('trip_in', models.DateField(max_length=100)),
                ('adults', models.CharField(max_length=100)),
                ('childrens', models.CharField(max_length=100)),
                ('amount', models.CharField(max_length=100)),
                ('childamount', models.CharField(max_length=100)),
                ('adultamount', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='packages_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=100)),
                ('days', models.CharField(max_length=100)),
                ('nights', models.CharField(max_length=100)),
                ('cnum', models.CharField(max_length=100)),
                ('day1', models.TextField()),
                ('day2', models.TextField()),
                ('day3', models.TextField()),
                ('day4', models.TextField()),
                ('day5', models.TextField()),
                ('day6', models.TextField()),
                ('day7', models.TextField()),
                ('day8', models.TextField()),
                ('day9', models.TextField()),
                ('day10', models.TextField()),
                ('day11', models.TextField()),
                ('day12', models.TextField()),
                ('day13', models.TextField()),
                ('day14', models.TextField()),
                ('day15', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('image', models.FileField(upload_to='package/')),
                ('specialcategory', models.CharField(max_length=100)),
                ('amount', models.CharField(max_length=100)),
                ('discamount', models.CharField(max_length=100)),
                ('discpercentage', models.CharField(max_length=100)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelapp.addloc_tb')),
            ],
        ),
        migrations.CreateModel(
            name='reg_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('guardian', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=100)),
                ('status', models.CharField(default='1', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='specialcatogory_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryfield', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='review_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=100)),
                ('image', models.FileField(upload_to='reviewimages/')),
                ('star', models.CharField(max_length=100)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('package_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelapp.packages_tb')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelapp.reg_tb')),
            ],
        ),
        migrations.CreateModel(
            name='payment_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=225)),
                ('date', models.DateField()),
                ('amount', models.CharField(max_length=225)),
                ('bookingid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelapp.booking')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelapp.reg_tb')),
            ],
        ),
        migrations.CreateModel(
            name='packageimages_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.FileField(upload_to='packageimages/')),
                ('image2', models.FileField(upload_to='packageimages/')),
                ('image3', models.FileField(upload_to='packageimages/')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelapp.packages_tb')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='bookpackageid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelapp.packages_tb'),
        ),
        migrations.AddField(
            model_name='booking',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelapp.reg_tb'),
        ),
    ]
